server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://paascloud-db-mysql:3306/mall?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: MasterMysql

    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      web-stat-filter:
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      stat-view-servlet:
        login-username: admin
        login-password: admin
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: paascloud-provider-elasticsearch:9300

mybatis:
  mapper-locations: classpath:dao/*.xml,classpath*:com/**/mapper/*.xml

logging:
  level:
    root: info



